### ISSUE TITLE
Ability to hide from status bar

### ISSUE THREAD

**Issue by skarchmit** [gao-sun/eul#104]
I'm running bartender4 to hide menu items, but I get this every time I boot.
Can we disable this check? 

![image](https://user-images.githubusercontent.com/8825870/99732663-ba979000-2a74-11eb-974e-d56582cfacfe.png)

**Comment by gao-sun** [comment]
yes

**Comment by gao-sun** [comment]
please try v1.4.6

**Comment by skarchmit** [comment]
It started to appear more often. (Used to just happen at launch, now even more frequent at random times)

**Comment by gao-sun** [comment]
![image](https://user-images.githubusercontent.com/14722250/100691894-a3d23100-33c4-11eb-8bcd-be129c1ae97f.png)

you need to uncheck "Check status item visibility" in preference panel

**Comment by gao-sun** [comment]
close for house keeping. also please try the latest version for a better experience. feel free to open a new issue if you have any concerns
