### ISSUE TITLE
[Feature] Show external drives and eject buttons

### ISSUE THREAD

**Issue by spoergsmaal** [gao-sun/eul#105]
Love the software, and would love it even more if it could show my connected external drives, how much space is left on them, and an eject button next to each drive.

For example, [MenuBar Stats](https://www.seense.com/menubarstats/) does it [like this](https://i.imgur.com/FNBd9nz.png)

**Comment by gao-sun** [comment]
yes

**Comment by gao-sun** [comment]
please try v1.5.4

**Comment by spoergsmaal** [comment]
> please try v1.5.4

It works! Thank you, great work.

One not very important suggestion: Maybe add an option to remove the eject button next to the built-in storage, "Macintosh HD", so people won't accidentally click it.

**Comment by gao-sun** [comment]
> Maybe add an option to remove the eject button next to the built-in storage, "Macintosh HD", so people won't accidentally click it.

sure! it won't work actually, but the suggestion is great. I'll remove the button for internal storages in the next release

**Comment by gao-sun** [comment]
@spoergsmaal please try v1.5.6, it now only shows eject button on external storages.

**Comment by gao-sun** [comment]
close for housekeeping. feel free to open a new one if anything doesn't work. cheers
