### ISSUE TITLE
Zip file name is prone to browser malware errors

### ISSUE THREAD

**Issue by rubengarciam** [gao-sun/eul#11]
Browsers like Chrome might think that the downloaded release is a malware file and would suggest the user to discard it.

<img width="422" alt="Screen Shot 2020-09-21 at 11 42 42 pm" src="https://user-images.githubusercontent.com/2044827/93774209-574fd400-fc64-11ea-93bd-8d9475eea817.png">

**Comment by gao-sun** [comment]
interesting, will try to eliminate this error or provide installation via brew cask

**Comment by gao-sun** [comment]
According to https://support.google.com/webmasters/thread/23193211 there's nothing I can do for now. hopefully it will be fixed in ~48hrs after release.

**Comment by gao-sun** [comment]
Homebrew/homebrew-cask#91294

**Comment by gao-sun** [comment]
now you can install via `brew cask install eul`. let me know if you have any concerns
