### ISSUE TITLE
Missing cool feature!

### ISSUE THREAD

**Issue by SoeWaiYan** [gao-sun/eul#110]
It would be very nice to have  gpu indicator! .Btw, I really enjoy using this software and  new widgets thz for your effort.

**Comment by gao-sun** [comment]
absolutely! please track this in #93 - i'll close this one for housekeeping.

**Comment by gao-sun** [comment]
please try v1.5.5

**Comment by SoeWaiYan** [comment]
I had and it is very nice. thank u!
