### ISSUE TITLE
bug report : can not sroll in components view

### ISSUE THREAD

**Issue by underwindfall** [gao-sun/eul#117]
# Context
- macOs Version **10.15.7 Catalina**
- eul verison **1.4.5**

# Description
After update to **1.4.5**,  the components menu is no longer able to scroll down anymore.

![image](https://user-images.githubusercontent.com/14819756/100515943-709f6000-3180-11eb-9935-e120f6701168.png)

**Comment by gao-sun** [comment]
taking a look

**Comment by gao-sun** [comment]
https://developer.apple.com/forums/thread/132809
seems a bug in SwiftUI. added back scroll indicator on Catalina in v1.4.6. please have a try.

**Comment by underwindfall** [comment]
> https://developer.apple.com/forums/thread/132809
> seems a bug in SwiftUI. added back scroll indicator on Catalina in v1.4.6. please have a try.

@gao-sun it seems like `brew` doesn't have find your version yet.  You need to push something or it'll updated it by it-self ?
![image](https://user-images.githubusercontent.com/14819756/100658417-4ea80800-334f-11eb-8c7d-09bbf92f1c93.png)

**BTW** also find it in `HomeCask` `github`, still not update it yet.
![image](https://user-images.githubusercontent.com/14819756/100658614-a8103700-334f-11eb-8fa3-4c1b2971a9be.png)

**Comment by underwindfall** [comment]
Updated : homebrew updated its version 
So **1.4.6** works like a charm. Bravo 👍 🍻

**Comment by gao-sun** [comment]
thanks for detailed reply! I forgot to update homebrew cask last night haha. @ran-dall [helped me](https://github.com/Homebrew/homebrew-cask/pull/93910) to do it. actually you can do the same thing if you want - just update version number and sha256 hash will be good to go
