### ISSUE TITLE
Start when login cannot be checked

### ISSUE THREAD

**Issue by zxitedu** [gao-sun/eul#118]
Start when login cannot be checked ，By the way, can you speed up the acquisition of CPU usage process，Hope to optimize in time, thank you(无法勾选登录时启动，顺便在提一个建议，能不能优化一下获取CPU使用进程的速度，希望及时优化，谢谢)

**Comment by zxitedu** [comment]
无法勾选登录时启动，顺便在提一个建议，能不能优化一下获取CPU使用进程的速度，希望及时优化，谢谢

**Comment by gao-sun** [comment]
screenshot/record?

**Comment by zxitedu** [comment]
![image](https://user-images.githubusercontent.com/48445631/100818243-ae53ff80-3484-11eb-8024-ba92c1ff2861.png)
Is to optimize the speed of the acquisition process here(就是优化一下这里获取进程的速度)

**Comment by gao-sun** [comment]
close due to no clear context. let me know if you have future updates
