### ISSUE TITLE
[bug]最新版Mac系统经常出现无响应的现象

### ISSUE THREAD

**Issue by guohui-ma** [gao-sun/eul#121]
在最新版的系统上，程序时常无响应。

**Context**
 - eul version:1.4.7
 - macOS version: 11.0.1
 - Device model: Macbook Pro 16 2016

**Comment by gao-sun** [comment]
please follow the instruction and paste debug output here

**Comment by ookangzheng** [comment]
Mine will be not responding on Big Sur with latest version

<img width="1188" alt="Screen Shot 2020-12-20 at 18 25 21" src="https://user-images.githubusercontent.com/6301735/102710927-fc745a00-42f0-11eb-96a7-4d7fdb63441e.png">

**Comment by gao-sun** [comment]
close due to no clear context. i optimized several performance issues recently. feel free to reopen it if you have updates. thanks
