### ISSUE TITLE
[bug]? eul menu notification

### ISSUE THREAD

**Issue by Oxeda** [gao-sun/eul#124]
I tried searching for this notification but I didn’t find anything, it’s probably not a bug anyway.

this is the notification that pops up after every restart:
![Captura de Pantalla 2020-12-09 a la(s) 14 38 00](https://user-images.githubusercontent.com/7676526/101685821-d4057980-3a2d-11eb-9e93-f44d027f35e9.jpg)

This is how eul’s menu settings look:
![Captura de Pantalla 2020-12-09 a la(s) 14 40 50](https://user-images.githubusercontent.com/7676526/101685540-812bc200-3a2d-11eb-88e5-2bba520dd3bd.jpg)

And this is how my eul looks on tray:
![Captura de Pantalla 2020-12-09 a la(s) 14 41 02](https://user-images.githubusercontent.com/7676526/101685508-7709c380-3a2d-11eb-9569-65825a5aac73.jpg)

I have just a few components as you can see, what am I doing wrong then?

thank you.

**Comment by gao-sun** [comment]
you are doing good i think. looks like a bug. will take a look

**Comment by gao-sun** [comment]
please try v1.5. let me know if it doesn't help.

**Comment by Oxeda** [comment]
hello, yesss, it seems that update solved the problem, thank you very much :)

**Comment by gao-sun** [comment]
glad it works
