### ISSUE TITLE
Can I install swiftUI or any prerequisite on Mojave?

### ISSUE THREAD

**Issue by KnowsCount** [gao-sun/eul#127]
I just hope I can use this on my Mojave.. 
I am frankly quite afraid of updating to Catalina or Big Sur as many told me there would be hardship – Catalina updated security mechanism and everything. But this app apparently only support 1.15+ and I therefore cannot use it. 
Or is there anyone who can convince me to update my OS? 🤣

**Comment by gao-sun** [comment]
hahaha Catalina & Big Sur are good (for me at least). I'm afraid there's no convenient to run SwiftUI apps on Mojave - the system doesn't have the framework and looks like Apple won't add support

**Comment by KnowsCount** [comment]
OK... I go to big sur later then. BTW cool app!
