### ISSUE TITLE
网速的数字变动会影响任务栏上的内容。

### ISSUE THREAD

**Issue by jememouse** [gao-sun/eul#13]
是否可以修复一下，比如预留一个较大的位置给数字。以免数字变动带来的抖动。

**Comment by gao-sun** [comment]
added to roadmap

**Comment by gao-sun** [comment]
please try the latest release and close the issue if looks good

**Comment by gao-sun** [comment]
closing for the completion of milestone, feel free to open a new one if the issue still exists
