### ISSUE TITLE
[feature request] add privacy info at AppStore

### ISSUE THREAD

**Issue by cfuentea** [gao-sun/eul#130]
Hello! it would be great if you can add some privacy info (new Apple Policy) on the App Store on the Next Update!

**Comment by gao-sun** [comment]
sure

**Comment by gao-sun** [comment]
![image](https://user-images.githubusercontent.com/14722250/134446419-a75d7e08-5dc7-4a2b-90c0-10076edfb43f.png)

**Comment by cfuentea** [comment]
nothing yet..?
