### ISSUE TITLE
Wrong CPU Temperature shown -81C°

### ISSUE THREAD

**Issue by Daniswiss** [gao-sun/eul#140]
Since version 1.5 and 1.5.1 the cpu temperature shows -81°C (minus degree!).

Shown on a 2017 iMac 21" 4k 3Ghz i5

**Comment by yklovett** [comment]
same happen to me.

2019 iMac 27''

**Comment by gao-sun** [comment]
I think the reason is #132 changed reading behavior of CPU temp from proximity to die, and in some Mac the number goes wrong. fixing now.

**Comment by gao-sun** [comment]
please try v1.5.2 to see if it helps

**Comment by gao-sun** [comment]
does the release fix this issue? @Daniswiss @yklovett

**Comment by Daniswiss** [comment]
Yes, seems to be fine again! thx!

**Comment by gao-sun** [comment]
you are very welcome
