### ISSUE TITLE
Can we enable discussions for this repo?

### ISSUE THREAD

**Issue by jevonmao** [gao-sun/eul#143]
GitHub Discussions is a collaborative communication forum for repositories. It allows people to easily ask question, have discussions, and make replies. 
Since we don't have Slack or email for communication, enable discussion would allow contributors on this project to ask questions about the codebase and things like that. What do you think, @gao-sun ?

Reference: https://docs.github.com/en/discussions/quickstart

**Comment by gao-sun** [comment]
yes!
