### ISSUE TITLE
Hope install from Mac App Store

### ISSUE THREAD

**Issue by HsiangHo** [gao-sun/eul#15]
Hope it can be released on Mac App Store  :)
Don't let some people steal your awesome work.

**Comment by gao-sun** [comment]
Unfortunately it won't pass the review due to SMC access :-(

**Comment by HsiangHo** [comment]
You can just try to remove some features for MAS and submit this app to review.
I think this app is much better than other similar apps.
Awesome UI.

**Comment by crownzdp** [comment]
hope install from home-brew

**Comment by gao-sun** [comment]
@HsiangHo thank you, will try!

**Comment by gao-sun** [comment]
@crownzdp sure, will add to homebrew cask

**Comment by gao-sun** [comment]
@HsiangHo https://apps.apple.com/us/app/eul/id1537133867
@crownzdp `brew cask install eul`
