### ISSUE TITLE
[bug] CPU Temperature incorrectly reported

### ISSUE THREAD

**Issue by thomasheeney** [gao-sun/eul#151]
<h3>Make sure there's no open issue for the same bug before submit.</h3>

**Describe the Bug**
The CPU temperature is currently showing as -85 degrees Celsius, but running `sudo powermetrics --samplers smc |grep -i "CPU die temperature"` reports 52 Celsius.

**Expected Behavior**
It should show the correct CPU temperature

**Screenshots**
<img width="307" alt="Screenshot 2021-01-22 at 11 24 13" src="https://user-images.githubusercontent.com/4903432/105485154-5e373380-5ca4-11eb-852e-cd320f1962e7.png">

**Context**
 - eul version: 1.5
 - macOS version: 11.2 Beta
 - Device model: iMac 5k 27 Inch 2017

**Debug Output**

``` bash
 loaded data from user defaults preference {
  "showCPUTopActivities" : true,
  "temperatureUnit" : "celius",
  "showIcon" : true,
  "language" : "en",
  "cpuMenuDisplay" : "usagePercentage",
  "smcRefreshRate" : 3,
  "showNetworkTopActivities" : false,
  "fontDesign" : "default",
  "textDisplay" : "compact",
  "networkRefreshRate" : 3,
  "checkStatusItemVisibility" : true
}
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI en1"] 
⚙️ loaded data from user defaults EulComponent {
  "availableComponents" : [
    "Disk"
  ],
  "activeComponents" : [
    "CPU",
    "Memory",
    "Fan",
    "Network"
  ],
  "showComponents" : true
}
⚙️ loaded data from user defaults componentConfig {
  "configs" : [
    {
      "showIcon" : true,
      "component" : "Disk",
      "showGraph" : false
    },
    {
      "showIcon" : true,
      "component" : "CPU",
      "showGraph" : false
    },
    {
      "showIcon" : true,
      "component" : "Fan",
      "showGraph" : false
    },
    {
      "showIcon" : true,
      "component" : "Network",
      "showGraph" : false
    },
    {
      "showIcon" : true,
      "component" : "Memory",
      "showGraph" : false
    }
  ],
  "converted" : true
}

```

**Is Related to a Crash?**
No.

**Comment by gao-sun** [comment]
would you mind to try the latest version? [a fix](https://github.com/gao-sun/eul/releases/tag/v1.5.2) has been placed in v1.5.2

**Comment by thomasheeney** [comment]
My apologies, I thought I updated through homebrew but apparently not! Working with 1.5.3. Thanks!
