### ISSUE TITLE
[bug]Reporting incorrect battery health

### ISSUE THREAD

**Issue by InsaneDuck** [gao-sun/eul#158]
Reporting incorrect battery health and max capacity on Macbook Air M1 
<img width="359" alt="Screenshot 2021-01-25 at 11 36 24" src="https://user-images.githubusercontent.com/39309626/105667886-2fb69400-5f02-11eb-913b-db1b6597b543.png">

**Comment by gao-sun** [comment]
good job M1 MacBook! will take a look soon

**Comment by gao-sun** [comment]
forgot to post here, should work in the latest version. feel free to re-open if the issue still exists
