### ISSUE TITLE
Style Light and Dark independently from macOS style

### ISSUE THREAD

**Issue by giuliomagnifico** [gao-sun/eul#159]
I tried to insert manually

`defaults write com.gaosun.eul NSRequiresAquaSystemAppearance -bool FALSE`

or TRUE, but nothing has changed. A check button in the UI app would be nice, but if you can explain where I'm wrong, it would be useful.

Thanks for the great app!

**Comment by gao-sun** [comment]
thanks for reporting. don't panic. I'll make an option to switch soon

**Comment by giuliomagnifico** [comment]
> thanks for reporting. don't panic. I'll make an option to switch soon

Great thanks, meanwhile can you provide me the correct "default write/boolean" to change the white UI to black by myself? It really hurts my eyes 😅 
 Thanks a lot!

**Comment by gao-sun** [comment]
> > thanks for reporting. don't panic. I'll make an option to switch soon
> 
> Great thanks, meanwhile can you provide me the correct "default write/boolean" to change the white UI to black by myself? It really hurts my eyes 😅
> Thanks a lot!

sure and you are very welcome!

**Comment by giuliomagnifico** [comment]
> > > thanks for reporting. don't panic. I'll make an option to switch soon
> 
> > 
> 
> > Great thanks, meanwhile can you provide me the correct "default write/boolean" to change the white UI to black by myself? It really hurts my eyes 😅
> 
> > Thanks a lot!
> 
> 
> 
> sure and you are very welcome!

Thanks, I wait for it :-)

**Comment by jevonmao** [comment]
@gao-sun I am trying to implement this feature. I will need to add new text which involves the localizations. Do I just leave the localization languages empty until someone fills it in? Should I open a new issue task for that?

**Comment by gao-sun** [comment]
@jevonmao thanks. please go ahead. you can use English for all l10ns in the beginning.

**Comment by jevonmao** [comment]
@giuliomagnifico The command you are using is probably not working because `appearance` is an UIKit thing, and most of the UI here is written in SwiftUI. Or maybe Apple just don't expose the dark mode settings for a particular app only:)

**Comment by gao-sun** [comment]
![image](https://user-images.githubusercontent.com/14722250/111644858-2e875080-883b-11eb-9c36-405d5aca8dbc.png)

a lot of things happened these days. but the good news is i'm back.

hopefully this is not too late, you can find the appearance dropdown under display section in the latest version now.

let me know if it doesn't work in Catalina (all my Macs have been updated to Big Sur)

**Comment by gao-sun** [comment]
Catalina will crash for some reason. this works for Big Sur. feel free to re-open if you have any concerns.
