### ISSUE TITLE
[feature request] provide a clean version of status bar logo

### ISSUE THREAD

**Issue by gao-sun** [gao-sun/eul#164]
from [reddit](https://www.reddit.com/r/MacOS/comments/l3ygc7/new_features_added_macos_status_monitoring_app/gkpcwmf?utm_source=share&utm_medium=web2x&context=3):

> I mean at the moment it is block white with a transparent swirl, which sticks out a lot aesthetically on my menu bar.
> If it was a white square outline, transparent background and a white swirl I think it would look really clean (ie white swirl in the middle of a white box outline, or even just a white swirl with no white box outline). Little suggestion but I think it would make the tool look more professional and clean.

**Comment by jevonmao** [comment]
I don't really understand. Is it talking about the app icon or the status bar drop down menu? Pictures will be nice.

**Comment by gao-sun** [comment]
@jevonmao no worries. I can handle this
