### ISSUE TITLE
[bug] not showing cpu temp. for M1 MacBook

### ISSUE THREAD

**Issue by MusaAqeel** [gao-sun/eul#166]
<h3>Make sure there's no open issue for the same bug before submit.</h3>

**Describe the Bug**

not showing cpu temp for m1 MacBook Air base model canada English

**Expected Behavior**

no
**Screenshots**

<img width="515" alt="Screen Shot 2021-01-25 at 4 57 55 PM" src="https://user-images.githubusercontent.com/77996753/105771389-7a4e0580-5f2e-11eb-8bb3-50382b515ee3.png">

**Context**
 - eul version:
 - macOS version:
 - Device model: 
 -
Mac OS 
<img width="229" alt="Screen Shot 2021-01-25 at 4 58 24 PM" src="https://user-images.githubusercontent.com/77996753/105771431-8b971200-5f2e-11eb-841b-a61d163c1e81.png">

**Debug Output**

``` bash
# PASTE OUTPUT HERE #
```

**Is Related to a Crash?**
no

**Comment by gao-sun** [comment]
I think the SMC key of CPU temperature for M1 has been changed. @jevonmao do you have a M1 Mac handy?

**Comment by jevonmao** [comment]
@gao-sun nope, I don't have M1 chip Mac which makes it hard to debug anything related to the M1

**Comment by gao-sun** [comment]
no problem. i'll try to debug this

**Comment by JeffWDH** [comment]
This project seems to be able to get the M1 temperature sensors, maybe you can get information from it:
https://github.com/freedomtan/sensors_cmdline

**Comment by gao-sun** [comment]
@JeffWDH this is great, thank you! will take a look this week.

**Comment by 6ix-Raptors** [comment]
Thanks! I really appreciate EUL!!

________________________________

**Comment by 6ix-Raptors** [comment]
I have one, also can you walk me though how i would dowload it and have the temprature displayed?

________________________________

**Comment by gao-sun** [comment]
@6ix-Raptors  that command line tool leverages some low level apis that i need some time to learn - sorry about inconvenience. you need Xcode to build and run that tool

**Comment by Musa4161** [comment]
> @6ix-Raptors that command line tool leverages some low level apis that i need some time to learn - sorry about inconvenience. you need Xcode to build and run that tool

Im 15 so im so lost, i still have the issue where it doesnt show cpu temp, i have Xcode but im not sure what and how to do what your saying in order for the temps to show

**Comment by jevonmao** [comment]
@Musa4161 It's a known issue for M1 Mac, everyone using Eul on an M1 chip Mac will not have CPU temperature display. Hopefully gao sun knows a little more Objective-C and can figure out the SMC stuff. I don't really understand what the code from that repo is doing.

**Comment by Musa4161** [comment]
Oh alright,
Im a noob but if you neeed some sort of help I got an M1 ready

**Comment by gao-sun** [comment]
@jevonmao @Musa4161 no worries guys, was too busy but will take a look once i finished current project (~one week)

**Comment by Musa4161** [comment]
Awesome, thanks!

**Comment by Yiyiyimu** [comment]
Hi @gao-sun maybe you could refer to this project
https://github.com/andreivdev/coolm1

**Comment by Musa4161** [comment]
Hello,

@gao-sun/eul ***@***.***> @gao-sun/eul
***@***.***>
@gao-sun/eul
***@***.***>
Yes, that would be really great as CoolM1 was made for M1 macs. Please try
to integrate the M1 temp monitoring features for the millions of M1 Macs
very eager to use eul to its fullest potential.

Thanks,

Musa

**Comment by gao-sun** [comment]
Thanks guys. Please see #213 for the awkward situation I'm facing. Promise that I'll do the compatibility job once the new model releases.

**Comment by naymapl** [comment]
Hi - on mac mini m1 have this same issue - Precentage of CPU working well but is none temp sensor data for CPU. This same is missing all data for GPU and missing Fan speed. Hope so @gao-sun will fix this soon. I love this app. Its simple, small and well design.

**Comment by ygg-musthafa** [comment]
Hi, It's been a year since the issue was open. Any Updates on this. Eul is the only elegant status monitoring app I could find. I have used this app in intel mac for some time. If it also works similarly in m1 mac it will help so many people. Please Update this issue.

**Comment by gyana-techy-ios** [comment]
Not able to get CPU temperature in M1 chip system.

**Comment by TomEstelrich** [comment]
Is there any update on that issue?
