### ISSUE TITLE
[bug] Eul.app inside Eul.app?

### ISSUE THREAD

**Issue by jdenormandie** [gao-sun/eul#167]
When I unzip eul, the app icon is a white circle-backslash.  When I try to launch the app I get an alert, "You can't open the application "eul" because it may be damaged or incomplete.

When I ran the debug, the output was "zsh: no such file or directory: /Applications/eul.app/Contents/MacOS/eul"

That made me curious, so I went into the package contents and discovered that it appears like the eul app is somehow inside another eul.app package?  See screen shots.  Eul.app is inside another eul.app.

**Context**
 - eul version: v1.5.7
 - macOS version: Big Sur 11.1
 - Device model: M1 and Intel MBP 13"

<img width="312" alt="Screen Shot 2021-01-26 at 8 26 31 AM" src="https://user-images.githubusercontent.com/74761361/105814480-c4c49600-5fb1-11eb-9462-e7156b40d0d2.png">
<img width="1319" alt="Screen Shot 2021-01-26 at 8 34 20 AM" src="https://user-images.githubusercontent.com/74761361/105814520-d443df00-5fb1-11eb-87e8-fd3eefcd702c.png">

**Comment by gao-sun** [comment]
this is really interesting. tried the steps below on Intel MacBook (macOS 11.1):
download the zip from release page -> unzip -> drag `.app` file to `Applications` folder -> works!

I assume it's an issue related to M1. will try to debug tonight.

**Comment by gao-sun** [comment]
in the mean time, would you mind to drag the inside `eul.app` to `/Applications` to see if it works?

**Comment by jdenormandie** [comment]
I just tried it again on my Intel MBP running Big Sur 11.1.  Same issue with the eul.app nested inside itself.

**Comment by jdenormandie** [comment]
Yes, this works fine on both M1 and Intel.

**Comment by gao-sun** [comment]
taking a look now

**Comment by gao-sun** [comment]
try on another MacBook but cannot reproduce. but i think i know the reason - if you list the structure under `eul.app.zip` you'll see something like this:

![image](https://user-images.githubusercontent.com/14722250/105874060-211dc900-6037-11eb-85df-01fd168b3750.png)

thus, the `.zip` file itself contains a folder which named `eul.app` (yes, macOS apps are actually folders). have you ever set an unzip preference like "create a new folder anyway"? that should be the cause.

**Comment by jdenormandie** [comment]
Yes, I just unchecked "create new folder" and eul.app unzipped as expected.  I used TheUnarchiver.app. Strange, why would would it append an ".app" to the folder it created when it unzipped eul?

**Comment by gao-sun** [comment]
@jdenormandie i think because of the filename `eul.app.zip`, thus it'll simply remove `.zip` suffix during unzipping. glad we figured it out :-)
