### ISSUE TITLE
[bug] Fatal error: No ObservableObject of type GpuStore found.

### ISSUE THREAD

**Issue by BookOfStopHere** [gao-sun/eul#168]
Crashed When launching App
`
Fatal error: No ObservableObject of type GpuStore found. A View.environmentObject(_:) for GpuStore may be missing as an ancestor of this view.: file SwiftUI, line 0
`
crash line in [GpuView.swift]
return gpuStore.usageAverageString ?? "N/A"

**Comment by gao-sun** [comment]
thanks for reporting! the info is enough i think. taking a look tonight.

**Comment by gao-sun** [comment]
it's an issue introduced by #145, will fix soon

**Comment by jevonmao** [comment]
Did I introduce this error in #145? What did I mess up? Far as I know, I didn't change any gpu related stuff.

**Comment by gao-sun** [comment]
@jevonmao I think you accidentally removed gpu store in shared stores - no worries. fixed in v1.5.8

**Comment by gao-sun** [comment]
should be good now @BookOfStopHere
