### ISSUE TITLE
Select which hard drives to monitor

### ISSUE THREAD

**Issue by jwwolff** [gao-sun/eul#169]
Allow the user to select which hard drives are used when displaying used and free space in the menu bar to allow time machine backups and bootcamp partitions to stay separate from the reported numbers.

**Comment by gao-sun** [comment]
suuuuure

**Comment by gao-sun** [comment]
should be available in the latest version

**Comment by gao-sun** [comment]
close for housekeeping. feel free to re-open if it doesn't work
