### ISSUE TITLE
Not Displaying

### ISSUE THREAD

**Issue by AstralGoGod** [gao-sun/eul#173]
**Describe the Bug**

The bug is that while the program runs it does not display itself in the menu bar and when I try to open it it still doesn't work.

**Expected Behavior**

It should be showing up in the menu bar

**Screenshots**

N/A

**Context**
Eul Version 1.5.8
macOS Version 11.1
MacBook Air (Retina, 13-inch, 2020)

**Debug Output**

⚙️ loaded data from user defaults preference {
  "networkRefreshRate" : 3,
  "fontDesign" : "default",
  "language" : "en",
  "smcRefreshRate" : 3,
  "temperatureUnit" : "celius",
  "showNetworkTopActivities" : false,
  "showIcon" : true,
  "showCPUTopActivities" : true,
  "checkStatusItemVisibility" : true,
  "textDisplay" : "compact",
  "cpuMenuDisplay" : "usagePercentage"
}
🔋 battery info 59 100 0 95 false false good battery 
🔋 battery info 59 100 0 95 false false good battery 
⚙️ loaded data from user defaults EulComponent {
  "availableComponents" : [
    "GPU",
    "Disk"
  ],
  "showComponents" : false,
  "activeComponents" : [
    "CPU",
    "Memory",
    "Fan",
    "Network",
    "Battery"
  ]
}
⚙️ loaded data from user defaults EulMenuComponent {
  "showComponents" : true,
  "activeComponents" : [
    "CPU",
    "GPU",
    "Fan",
    "Memory",
    "Network",
    "Battery",
    "Bluetooth",
    "Disk"
  ],
  "availableComponents" : [

  ]
}
shell with ["system_profiler SPDisplaysDataType -xml"] 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
⚙️ loaded data from user defaults componentConfig {
  "configs" : [
    {
      "showGraph" : false,
      "component" : "CPU",
      "showIcon" : true
    },
    {
      "showGraph" : false,
      "component" : "GPU",
      "showIcon" : true
    },
    {
      "showGraph" : false,
      "component" : "Fan",
      "showIcon" : true
    },
    {
      "showGraph" : false,
      "component" : "Battery",
      "showIcon" : true
    },
    {
      "showGraph" : false,
      "component" : "Network",
      "showIcon" : true
    },
    {
      "showGraph" : false,
      "component" : "Disk",
      "showIcon" : true
    },
    {
      "showGraph" : false,
      "component" : "Memory",
      "showIcon" : true
    }
  ],
  "converted" : true
}
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔵🦷 state update 5 
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
✅ status item is visible 
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 59 100 0 95 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 58 100 0 104 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 
shell with ["route get 0.0.0.0 | grep interface | awk \'{print $2}\'"] 
shell with ["netstat -bI utun2"] 
🔋 battery info 57 100 0 94 false false good battery 

It kept looping the last message for 10 mins.

**Comment by jevonmao** [comment]
@AstralGoGod Did you get a pop up saying Eul is hidden by system? Please try this: reduce the number of components until it shows up. Because when you have lots of components on a small screen, there isn't enough space.

**Comment by AstralGoGod** [comment]
I did just get that popup, weird. I had to force quit the app and restart my computer for it to do so though. Thank you!
