### ISSUE TITLE
[bug] Wrong  Battery Max Cap on Macbook Pro M1

### ISSUE THREAD

**Issue by slinker-hiwa** [gao-sun/eul#184]
Max Battery Cap is 100mah. [](url)
<img width="337" alt="Screen Shot 2021-02-09 at 14 22 44" src="https://user-images.githubusercontent.com/30239019/107329292-8c10da80-6ae2-11eb-8aa8-3101e68737f6.png">

**Comment by gao-sun** [comment]
should work now - please try the latest version (v1.5.13)

**Comment by btannous** [comment]
it does work on my MBA M1

**Comment by gao-sun** [comment]
@btannous yeah thanks, i think it's fixed on the latest version
@slinker-hiwa close this issue for house-keeping, feel free to re-open if the bug still exists
