### ISSUE TITLE
黑果，打开没反应。哪有日志可以看看？

### ISSUE THREAD

**Issue by 24** [gao-sun/eul#2]

**Comment by findyy99** [comment]
Big Sur pb1 也打不开

**Comment by gao-sun** [comment]
我去尝试展示一下错误日志

**Comment by gao-sun** [comment]
https://github.com/gao-sun/eul/releases/latest

请尝试下载最新版看是否能解决问题

**Comment by findyy99** [comment]
@gao-sun `2020-09-15 14:31:02.913 eul[2757:202140] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.`
仍然不行。

**Comment by gao-sun** [comment]
好的，我去尝试复现一下

**Comment by 24** [comment]
@gao-sun 

2020-09-15 21:17:16.600 eul[3168:53224] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
[1]    3168 illegal hardware instruction  /Applications/eul.app/Contents/MacOS/eul

不过，我是nuc 的黑果，istat 能获得温度。

![image](https://user-images.githubusercontent.com/1859160/93215495-130e9080-f799-11ea-9abb-fcda3a3b452d.png)

**Comment by gao-sun** [comment]
@findyy99 @24 这个提示似乎是 SwiftUI 自身的原因，我在本地 Xcode 没能复现。

刚升级了 Big Sur ，复现了 crash 问题并已修复。烦请再次下载新版 (v1.0.4) 尝试。

**Comment by gao-sun** [comment]
本地采用 1.0.3 版已复现 crash 的情况，1.0.4 应该没问题了

**Comment by findyy99** [comment]
@gao-sun 可以了，只是稍稍感觉图标有点占地方，可不可以添加一个整合的图标的设置？

**Comment by gao-sun** [comment]
@findyy99 没问题，已经在现代计划里了

**Comment by gao-sun** [comment]
@24 我看到还有 `[1] 3168 illegal hardware instruction` 的问题，这个可能是不同硬件导致的，可能有些难调试

**Comment by 24** [comment]
@gao-sun 没事，黑果，如果出现这个应该正常把。

**Comment by 24** [comment]
<img width="356" alt="Screen Shot 2020-09-24 at 3 25 09 PM" src="https://user-images.githubusercontent.com/1859160/94113904-2c3ecd80-fe7a-11ea-90a7-c9d6acb6b505.png">
xi新版本完全可以了。
厉害，

**Comment by gao-sun** [comment]
@24 我看到有一些读不到的数据（风扇和电池），我去做一下优化

**Comment by 24** [comment]
@gao-sun   
电池读不到，是因为，我这是nuc 台式机，
风扇的话， 那个 iStat 也读不到风扇数据，这个风扇感觉不好弄
:)
