### ISSUE TITLE
[M1 + M1 Pro. + M1 Max]

### ISSUE THREAD

**Issue by MusaAqeel** [gao-sun/eul#228]
Please develop a version that will work with Apple Silicon. The temperature monitoring does not work with my M1 mac, it will probably not working with the new Pro devices. If you search "Coolm1" on github you can see a project that just has the temp monitoring, but without any of the other features of eul. It would be great if this version can be dev. Thanks for your time

**Comment by jevonmao** [comment]
The Coolm1 repo you mentioned seems to be just a wrapper on top of https://github.com/fermion-star/apple_sensors should not be too hard to fully support Apple Silicon, as long as solution exist for interfacing with lower level system stuff like that library.

**Comment by naymapl** [comment]
Hi. Any news about M1 machines ? I use rhis app on macbook pro with intel and everything runing perfect. I have Fan speed, all sensors and CPU temp. On M1 mac mini no fan speed, no gpu, no other temp sensor. I love your app - is simple end well design but not working with nem amr64 processors and machines. Any chance to update this app ??

**Comment by asyba** [comment]
any news?

**Comment by gao-sun** [comment]
just got my M1 Pro laptop, will do it in few days

**Comment by 6ix-Raptors** [comment]
> just got my M1 Pro laptop, will do it in few days

Amazing! I am very excited, and oh enjoy that beast.

**Comment by naymapl** [comment]
We waiting for m1 version 🥇

**Comment by 6ix-Raptors** [comment]
So excited for eul for M1! Its so hard to wait but Its gonna be worth the wait!!

**Comment by naymapl** [comment]
Hello - any news about arm64 version ?

**Comment by henjue** [comment]
We waiting for m1 version 🥇

**Comment by 6ix-Raptors** [comment]
So excited for the M1 version!!

**Comment by shuangwei-Ye** [comment]
> So excited for the M1 version!!

have new version ?

**Comment by 6ix-Raptors** [comment]
> > So excited for the M1 version!!
> 
> have new version ?

Not yet, still waiting...

**Comment by 6ix-Raptors** [comment]
> just got my M1 Pro laptop, will do it in few days

Can you please give us an idea of when Eul for Apple Silicon will be available? Thanks :)

**Comment by 6ix-Raptors** [comment]
Take your time but we are very eager to get that Silicon version!

**Comment by naymapl** [comment]
@gao-sun 3 weeks gone and any info from you ? Are you ok ? Thank you so much for any details. Many people waiting for this app :D

**Comment by 6ix-Raptors** [comment]
Honestly just take your time but I just want to know if your doing ok! Haven't heard from you in a while.

**Comment by MusaAqeel** [comment]
Will there be an M1 + M1 Pro + M1 Max version any time soon @gao-sun? If so we are all very eager to use it!

**Comment by MusaAqeel** [comment]
You alive @gao-sun? I understand if your busy just please give us an update. Thanks.

**Comment by gao-sun** [comment]
I'm alive. Sorry I was mainly working on my startup these days and having a cold in the past week.

Xcode has been downloaded on my M1 laptop and now I'm picking up my Swift knowledge and inspect the broken parts - I'll open a PR soon to let you guys know the progress. Thanks for waiting.

**Comment by naymapl** [comment]
Hey @gao-sun hope so you will find some time to fix all this issues and compiling app for Apple Silicon. Good luck and all the best for you.

**Comment by gao-sun** [comment]
yeah I'm working on the sensors but I just have limited time on this (weekends) so I can't give you the exact timeline. Meanwhile you can try [stats](https://github.com/exelban/stats) as the author is actively contributing to the project.

**Comment by naymapl** [comment]
@gao-sun I use allready stat app but your looks much better for me - I like your design and icons - all looks nice. In Stat app can`t use to much colors and no option to set up icons for CPU or RAm or GPU like in your app

<img width="408" alt="Zrzut ekranu 2022-01-29 o 11 12 42" src="https://user-images.githubusercontent.com/24625283/151657039-7889f1bb-eb24-48ca-a638-b45fa9b3063c.png">

**Comment by gao-sun** [comment]
@naymapl thank you! I've opened a PR for M1 compatibility work. You can follow the status there. Cheers.

**Comment by MusaAqeel** [comment]
> I'm alive. Sorry I was mainly working on my startup these days and having a cold in the past week.

Thank you and i'm glad to know your doing alright!

**Comment by gao-sun** [comment]
please see #243

**Comment by MusaAqeel** [comment]
@gao-sun Thanks for letting us know. I wish the best for your startup.
