### ISSUE TITLE
菜单栏字体

### ISSUE THREAD

**Issue by SnowsonZ** [gao-sun/eul#230]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/12555482/139807189-43ea29f6-c133-4701-b531-e16175f1006e.png">

如图，菜单栏字体过小，不容易辨识，期望下个版本能加粗，加大，或者自定义字体？哈哈哈~

**Comment by gao-sun** [comment]
Please follow the guideline for issues. I'll close this one for house-keeping purpose.
