### ISSUE TITLE
[bug]Launch at login not work

### ISSUE THREAD

**Issue by sheiy** [gao-sun/eul#247]
<h3>Make sure there's no open issue for the same bug before submit.</h3>

**Describe the Bug**
Launch at login not work

**Expected Behavior**
work will 

**Screenshots**

**Context**
 - eul version: 1.6.2
 - macOS version: 12.4 (21F79)
 - Device model: M1

**Debug Output**

Can't see any error

``` bash
# PASTE OUTPUT HERE #
```

**Is Related to a Crash?**

**Comment by Smatjoy** [comment]
I have the same problem on m3 macbook air.
how can I fix?

**Comment by sheiy** [comment]
@Smatjoy I use Stats for now
