### ISSUE TITLE
[feature] new dropdown menu design

### ISSUE THREAD

**Issue by SukkaW** [gao-sun/eul#3]
Show info through dropdown menu instead of showing every element inside menu bar.

**Comment by gao-sun** [comment]
Do you mean an aggregated drop down view for all info?

**Comment by SukkaW** [comment]
> Do you mean an aggregated drop down view for all info?

Yeah.

**Comment by gao-sun** [comment]
Cool idea, added to roadmap

**Comment by gao-sun** [comment]
just released a new version, please try v1.1

**Comment by SukkaW** [comment]
> just released a new version, please try v1.1

Yeah!
