### ISSUE TITLE
CPU Graph

### ISSUE THREAD

**Issue by AlecRust** [gao-sun/eul#31]
This project looks great, would love to replace iStat Menus with it!

The main thing I use from iStat Menus is the CPU graph in the menu bar. I don't see this in the screenshots for Eul, are there any plans to add this?

When I click the graph in the menu bar it opens a dropdown with the highest CPU at the top:

![screenshot](https://i.imgur.com/dSqaBZp.png)

**Comment by gao-sun** [comment]
please try v1.4.5 with status bar CPU/memory graph available. will add the graph in menu view soon

**Comment by gao-sun** [comment]
please try v1.4.7

**Comment by L-U-C-K-Y** [comment]
Hi all

Is this intended behavior on refresh?

![Kapture 2020-12-22 at 10 13 14](https://user-images.githubusercontent.com/14868134/102871120-4fa7f300-443e-11eb-97c2-83a49467cd2b.gif)

**Comment by gao-sun** [comment]
@L-U-C-K-Y  this is not normal - please track the issue in #128.

closing for housekeeping
