### ISSUE TITLE
Battery charging icon does not respond simultaneously when its status changes

### ISSUE THREAD

**Issue by haohanyang** [gao-sun/eul#38]
There is seconds-long latency in the battery icon status response. It would be better if the icon changes immediately after the charging status alters

**Comment by haohanyang** [comment]
I wonder if there is some even emitter mechanism under the hood of Cocoa development

**Comment by gao-sun** [comment]
> I wonder if there is some even emitter mechanism under the hood of Cocoa development

sounds cool, will do some investigation

**Comment by gao-sun** [comment]
according to [this post](https://stackoverflow.com/q/51275093/12514940) it seems there's no macOS equivalent to [batteryStateDidChangeNotification](https://developer.apple.com/documentation/uikit/uidevice/1620052-batterystatedidchangenotificatio). maybe you can set SMC refresh rate to 1s for a quicker responding

![Uploading image.png…]()

**Comment by gao-sun** [comment]
closing this issue. let me know if you have any ideas/concerns
