### ISSUE TITLE
启动后没反应

### ISSUE THREAD

**Issue by bg4hkq** [gao-sun/eul#5]
baoz@baozMBP  ~  /Applications/eul.app/Contents/MacOS/eul
⚙️ loaded data from user defaults {
  "activeComponents" : [
    "CPU",
    "Fan",
    "Memory",
    "Battery",
    "Network"
  ],
  "temperatureUnit" : "celsius",
  "textDisplay" : "compact",
  "language" : "zh-Hans",
  "availableComponents" : [

  ]
}
2020-09-14 15:19:28.708 eul[10553:661079] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.

**Comment by bg4hkq** [comment]
Catalina 10.15.6 (19G2021)

**Comment by bg4hkq** [comment]
等了好久出来了菜单，但是点菜单反应超级慢，不知道是哪里卡住了。后台再没更多日志。

**Comment by gao-sun** [comment]
感谢反馈，我debug一下

**Comment by gao-sun** [comment]
https://github.com/gao-sun/eul/releases/latest

请尝试下载最新版看是否能解决问题，如果仍然存在还麻烦提供一下电脑型号

**Comment by missdeer** [comment]
相同问题，最近版一样。
10.15.6, 2017 款 iMac

**Comment by bg4hkq** [comment]
问题依旧，MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

**Comment by gao-sun** [comment]
好的我去尝试找到电脑复现一下

**Comment by gao-sun** [comment]
已经复现问题并修复，本地测试 OK，还烦请下载 1.0.4 版本尝试

**Comment by missdeer** [comment]
10.15.6, 2017 款 iMac, 1.0.4
```
Illegal instruction: 4
```

**Comment by bg4hkq** [comment]
我这边测试问题依旧，但等一分钟左右能出来界面，鼠标hover到界面上就转菊花

**Comment by missdeer** [comment]
找到出错的代码行了：

https://github.com/gao-sun/eul/blob/9b890d725d4fa540497e17a8e4e4afd6e5fe10d2/eul/Utilities/Info.swift#L43

在Xcode里跑起来会报`Double value cannot be converted to Int because it is either infinite or NaN`，这行改掉就好了

**Comment by gao-sun** [comment]
@bg4hkq 我和你的电脑型号一样，没有遇到你的情况，有些奇怪
@missdeer 非常感谢！我去改一下

**Comment by gao-sun** [comment]
> 找到出错的代码行了：
> 
> https://github.com/gao-sun/eul/blob/9b890d725d4fa540497e17a8e4e4afd6e5fe10d2/eul/Utilities/Info.swift#L43
> 
> 在Xcode里跑起来会报`Double value cannot be converted to Int because it is either infinite or NaN`，这行改掉就好了

1.0.6 已更新，解决了这个问题

**Comment by bg4hkq** [comment]
复测，1.0.6版本，问题依旧，界面出来之后无法操作，一直转圈圈。
会不会是取api.github.com的时候卡住了？

**Comment by gao-sun** [comment]
@bg4hkq 有可能，我断网情况下试试，感谢反馈

**Comment by bg4hkq** [comment]
v1.4.3复测好了。
