### ISSUE TITLE
在设置里面点击几下左边工具栏会闪退

### ISSUE THREAD

**Issue by crownzdp** [gao-sun/eul#60]

**Comment by gao-sun** [comment]
tried to click the left tabs multiple times but cannot reproduce. would you mind to provide your device and OS info?

**Comment by crownzdp** [comment]
> tried to click the left tabs multiple times but cannot reproduce. would you mind to provide your device and OS info?
mbp 16inch - macOS 10.15.7

**Comment by crownzdp** [comment]
this is gif : https://sm.ms/image/OM7sSuCRp4wnDcK

**Comment by gao-sun** [comment]
taking a look

**Comment by reputati0n** [comment]
version:1.4.1
my device: MBP 13 2020 macOS 10.15.7
the problem is still

**Comment by gao-sun** [comment]
will take a look on Catalina tonight

**Comment by gao-sun** [comment]
please try `v1.4.2`, closing it since duplicate. please track this issue in #68
