### ISSUE TITLE
Top network utilization processes

### ISSUE THREAD

**Issue by ricky-wong** [gao-sun/eul#63]
Can we get network utilization by process and show the top users? Thank you!

**Comment by gao-sun** [comment]
We do have this feature but it's disabled by default due to some potential performance issue in `nettop` (#18 #35)

You can still try it, please go Preferences -> Menu View and check "Show network top activities"

Let me know if you have any questions

**Comment by ricky-wong** [comment]
I was looking for such a setting before I opened this issue, but I couldn't find it. 🤔 
![image](https://user-images.githubusercontent.com/704713/98481164-4116bc80-21ad-11eb-90d9-6742bbc00b30.png)

**Comment by gao-sun** [comment]
please try v1.4. looks like auto-update doesn't get the right response

**Comment by gao-sun** [comment]
https://github.com/gao-sun/eul/releases/tag/v1.4

**Comment by ricky-wong** [comment]
Nice, thanks
