### ISSUE TITLE
Show load average in CPU section

### ISSUE THREAD

**Issue by kcmannem** [gao-sun/eul#65]
Load average is a pretty important stat I look other than just cpu %. It'd be a nice to have.

**Comment by gao-sun** [comment]
sure

**Comment by koenlek** [comment]
This would be really nice to have. Especially in the menu bar. The full menu could show the standard 3 load averages (1, 5 and 15 minutes), and the menu bar would prob show the 1 minute average (could be made configurable though?). To me, load averages give a much nicer signal of how heavy your system (cpu) is loaded than the cpu percentage (which is too noisy to me).

By the way, thanks for the great work on this tool. I just discovered it recently and I really like it!

**Comment by gao-sun** [comment]
@koenlek thank you, really nice advice. absolutely will implement

**Comment by gao-sun** [comment]
please try v1.4.6

**Comment by koenlek** [comment]
Works like a charm. Thanks!!
