### ISSUE TITLE
Bring free/used memory and storage in the same order

### ISSUE THREAD

**Issue by romanhaa** [gao-sun/eul#67]
Hi there,

this is a nice tool, thanks for developing it! I noticed that, at least for me, the free/used parts of memory and storage are not in the same order, which can be a little confusing. That is, the free memory is shown on top of the used memory, but for storage the "free" part is shown underneath the used storage. It would be nice if this could be put into the same order, possibly with a setting in the preferences to decide whether "free" or "used" should be shown on top of the other.

![Screenshot 2020-11-09 at 09 41 55](https://user-images.githubusercontent.com/18103560/98518537-cebae080-226f-11eb-820d-e392b849177d.png)

Cheers,
Roman

**Comment by gao-sun** [comment]
sure thing. thank you for your feedback

**Comment by gao-sun** [comment]
just swapped order in `v1.4.2` and will try to make it configurable in `v1.5`

**Comment by romanhaa** [comment]
Excellent, works like a charm! Thanks a lot :)
