### ISSUE TITLE
Battery status of bluetooth devices

### ISSUE THREAD

**Issue by Tealk** [gao-sun/eul#69]
Hello,

would it be possible to display the battery status of the Bluetooth?

**Comment by gao-sun** [comment]
yes

**Comment by gao-sun** [comment]
please try v1.5.4. should work now.

**Comment by gao-sun** [comment]
release in 15 min

**Comment by gao-sun** [comment]
sorry I mean v1.5.3, too excited to launch this feature

**Comment by gao-sun** [comment]
![Uploading image.png…]()

it's disabled by default, please add bluetooth component in menu view preference

**Comment by Tealk** [comment]
I am curious to see what you have conjured up

**Comment by Tealk** [comment]
![CleanShot 2021-01-22 at 17 33 51](https://user-images.githubusercontent.com/12276250/105518007-074b5180-5cd8-11eb-9fd1-f6c01e82f62c.jpg)
im in love
