### ISSUE TITLE
First status bar click not recognized

### ISSUE THREAD

**Issue by rfuehrer** [gao-sun/eul#73]
After starting the application, the first click on the icon of the status bar is not accepted. Only the second click opens the application. The problem exists in versions 1.4.1 and 1.4.2.

For clarification I have recorded the behaviour as video.

![eul_first_click](https://user-images.githubusercontent.com/25303664/98556304-31799f80-22a3-11eb-9484-a80420960a5d.gif)

**Comment by gao-sun** [comment]
yes I noticed that as well. will try to fix. thanks

**Comment by gao-sun** [comment]
found the issue. fixing in next relase https://github.com/gao-sun/eul/pull/74
