### ISSUE TITLE
Fixed sizing for menu bar components

### ISSUE THREAD

**Issue by itsnwa** [gao-sun/eul#79]
First off, what a great app! Thank you so much for putting in the effort and releasing it to the public.

I noticed that the menu bar components are changing size based on it's content, which leads to a lot of jumping.
Would be nice to have a fixed size for each component, and if possible, the ability to change the spacing between them in the settings.

**Comment by gao-sun** [comment]
thanks. that would be a great idea. just updated [v1.4.3](https://github.com/gao-sun/eul/releases) for a less "jumpy" experience. will add fixed size option in the future

**Comment by itsnwa** [comment]
@gao-sun the build is missing from the release assets in v1.4.3

**Comment by gao-sun** [comment]
sorry, just updated

**Comment by gao-sun** [comment]
I believe now menu bar components are quite "fixed". close for house-keeping. feel free to create a new issue if the latest version doesn't help
