### ISSUE TITLE
very high cpu usage when eul runs

### ISSUE THREAD

**Issue by MackHarry** [gao-sun/eul#84]
When running eul on macOS big sur, I get very high cpu usages, as reported by activity monitor. CPU usage goes up to 42%, even 100% at times. This heats up the cpu quite a bit, and fans are permanently audibly working, and sadly renders eul unusable for me. Not sure what's going  on here, perhaps it has something to do with #35 ?

**Comment by gao-sun** [comment]
Did you check “show network top activities”? That could be an issue as you said

**Comment by gao-sun** [comment]
close for housekeeping. this is possibly duplicate of #87, let's track there. thank you for feedback and let me know if you have any concerns.
