### ISSUE TITLE
Network doesn't work

### ISSUE THREAD

**Issue by arastu** [gao-sun/eul#85]
Hi, thanks for creating this cool app, the network indicator always stays at zero (up and down), I'm using eul v1.4.3 on macOS Big Sur.

**Comment by gao-sun** [comment]
currently active network device is auto-detected (which may have the error result I think) will try to provide manual selection in v1.5

**Comment by jevonmao** [comment]
This is from a looong time ago so I'm going to close this. Also this issue should be fixed during the past months.

**Comment by gao-sun** [comment]
@arastu sorry. this shouldn't be closed before. please try v1.6. auto-detect is smarter now and you can manually choose network port to detect

**Comment by arastu** [comment]
no problem @gao-sun, checked it out just now, it seems to be working fine. thanks again.

**Comment by arastu** [comment]
No problem @gao-sun, I just checked it out and it seems to be working fine. Thanks again.
