### ISSUE TITLE
Documentation / tooltip / readme additon

### ISSUE THREAD

**Issue by piotr-yuxuan** [gao-sun/eul#97]
Hello, thanks for this nice project! I've started to use it, it really is nice. However I'm having some quizzical time to figure out the difference between battery health, and battery condition?

**Comment by gao-sun** [comment]
battery health is `max capacity / design capacity`, while battery condition is an enum value provided by system API

**Comment by gao-sun** [comment]
besides these two wordings, what kind of docs would you want to add in readme?

**Comment by gao-sun** [comment]
close for housekeeping. feel free to re-open if you have further questions.
